Azure/Community-Policy

- Policies/App Service/allowed-appservicesplan-skus/README.md
- Policies/App Service/allowed-appservicesplan-skus/azurepolicy.json
- Policies/App Service/allowed-appservicesplan-skus/azurepolicy.parameters.json
- Policies/App Service/allowed-appservicesplan-skus/azurepolicy.rules.json
I've created this policy to restrict which App Services plans SKU can be used. It's like the one for VM SKU with the difference we don't have strongtype for App Services SKUs.
I've used the folder App Services to host my policy as it's the one used on main azure policy repository.
Thanks in advance !
> Add allowed app services plan SKU policy

- Policies/Network/deny-vms-not-in-a-specific-subnet-from-being-part-of-a-backend-pool/azurepolicy.rules.json
Extra metadata was copied in on accident which was breaking PowerShell deployments of policy.
> fixing deny-vms-not-in-a-specific-subnet-from-being-part-of-a-backend-pool azurepolicy.rules.json

- Policies/Monitoring/apply-diagnostic-setting-subscription-storage-account/azurepolicy.json
- Policies/Monitoring/apply-diagnostic-setting-subscription-storage-account/azurepolicy.rules.json
Made a mistake in one of the role ids for the storage account
> Fix role id's in diagnostics settings policy

- Policies/Network/append-nsg-rule/target-all-nsgs-by-region/azurepolicy.json
- Policies/Network/append-nsg-rule/target-all-nsgs-by-region/azurepolicy.parameters.json
- Policies/Network/append-nsg-rule/target-all-nsgs-by-region/azurepolicy.rules.json
- Policies/Network/append-nsg-rule/target-all-nsgs/azurepolicy.json
- Policies/Network/append-nsg-rule/target-all-nsgs/azurepolicy.rules.json
- Policies/Network/append-nsg-rule/target-nsg-by-suffix/azurepolicy.json
- Policies/Network/append-nsg-rule/target-nsg-by-suffix/azurepolicy.rules.json
Previous logic would detect additional resources beyond just the nsg. This resulted in many non-compliant results even when all resources were compliant. Logic has been corrected.
> fixing detection logic and param indent error

- Policies/Network/deny-route-nexthopvirtualappliance/README.md
- Policies/Network/deny-route-nexthopvirtualappliance/azurepolicy.json
- Policies/Network/deny-route-nexthopvirtualappliance/azurepolicy.parameters.json
- Policies/Network/deny-route-nexthopvirtualappliance/azurepolicy.rules.json
Deny route with address prefix 0.0.0.0/0 not pointing to the virtual appliance. Both creating routes as a [standalone resource](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/routetables/routes) or [nested within their parent resource route table](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/routetables) are considered.
> Initial commit of deny-route-nexthopvirtualappliance

- Policies/Network/modify-subnet-nsg/README.md
- Policies/Network/modify-subnet-nsg/azurepolicy.json
- Policies/Network/modify-subnet-nsg/azurepolicy.parameters.json
- Policies/Network/modify-subnet-nsg/azurepolicy.rules.json
Adds the default network security group to subnets in case there is none. Nothing happens when another network security group is already associated with the subnet.
> Initial commit of modify-subnet-nsg

- Policies/PostgreSQL/Diagnostic Settings
I created a Policy Definition for the Azure Database for PostgreSQL service which creates an audit event when specific log (i.e. PostgreSQLLogs) and metric categories (i.e. AllMetrics) in the Diagnostic Settings are not send to a specific Log Analytics Workspace. 
You can also use this Policy Definition for other Azure Services by changing the resource type on line 25. Next to that, additional log and metric categories can be added by creating new count loops.
> PostgreSQl: Added a Policy Definition on the Diagnostic Settings

- Policies/Monitoring/deploy-diagnostic-setting-for-activity-log-event-hub/azurepolicy.json
workspaceId will be null if we are only defining event hub and this policy will never show as compliant. adjusting to eventHubAuthorizationRuleId to match the value this will create.
> Change Event Hub Azure Activity Policy to point to EH Rules instead of LA Workspace

- Policies/App Service/audit-appservicesbackend-appgw/README.md
- Policies/App Service/audit-appservicesbackend-appgw/azurepolicy.json
- Policies/App Service/audit-appservicesbackend-appgw/azurepolicy.parameters.json
- Policies/App Service/audit-appservicesbackend-appgw/azurepolicy.rules.json
Custom policy requires that HTTP(S) triggered apps require App GW Front-End so that inbound ports are not opened on apps
> App Service Apps require App Gateway Front End

- Policies/Network/deny-private-endpoint-if-not-in-specific-subnet/README.md
- Policies/Network/deny-private-endpoint-if-not-in-specific-subnet/azurepolicy.json
- Policies/Network/deny-private-endpoint-if-not-in-specific-subnet/azurepolicy.parameters.json
- Policies/Network/deny-private-endpoint-if-not-in-specific-subnet/azurepolicy.rules.json
- Policies/Network/deploy-private-dnszone-vnet-link-to-vnets/README.md
- Policies/Network/deploy-private-dnszone-vnet-link-to-vnets/azurepolicy.json
- Policies/Network/deploy-private-dnszone-vnet-link-to-vnets/azurepolicy.parameters.json
- Policies/Network/deploy-private-dnszone-vnet-link-to-vnets/azurepolicy.rules.json
This policy enforces all private endpoints to be deployed into subnets that follow a specific prefix name. Also supports exemptions for specific Private Endpoint Group IDs if required.
> Network: Deny if a Private Endpoint is not deployed into a specific Subnet Prefix & Create DNS Zone vNET Integration Policy

- Policies/Kubernetes/ArcPolicyExtension_Deploy
AuditIfNotExists and DeployIfNotExists policy rules for deploying Azure Policy's extension on your Azure Arc-enabled clusters.
> Deploy Azure Policy's extension on your Azure Arc-enabled Clusters

- Policies/Monitoring/deploy-diagnostic-setting-for-aks-event-hub/README.md
- Policies/Monitoring/deploy-diagnostic-setting-for-aks-event-hub/azurepolicy.json
- Policies/Monitoring/deploy-diagnostic-setting-for-aks-event-hub/azurepolicy.parameters.json
- Policies/Monitoring/deploy-diagnostic-setting-for-aks-event-hub/azurepolicy.rules.json
This request allows configuring Diagnostic settings to event hub for each individual log value instead of just all logs and all metrics.  This ensure that the policy compliance matches the configuration.
> DINE policy for granular AKS Diagnostic Settings to Event Hub

- Policies/Authorization/disallowed-role-definitions/azurepolicy.json
- Policies/Authorization/disallowed-role-definitions/azurepolicy.parameters.json
- Policies/Authorization/disallowed-role-definitions/azurepolicy.rules.json
Fixes 3 issues with the current policy:
- The function which splits the role definition doesn't work - it triggers an error during policy evaluation
- the default value for the 'exemptPrincipalIDs' parameter is a string, but the parameter type is array, causing an error during definition creation
- The parameter description for 'roleDefinitionIds' is wrong - it said the opposite of what it should say
> fix broken 'disallowed role definition' policy

- Policies/Network/address-space-should-be-pre-allocated-for-region/README.md
- Policies/Network/address-space-should-be-pre-allocated-for-region/azurepolicy.json
- Policies/Network/address-space-should-be-pre-allocated-for-region/azurepolicy.parameters.json
- Policies/Network/address-space-should-be-pre-allocated-for-region/azurepolicy.rules.json
Following the release of the ability to update the address space of a peered VNET (and resync), it becomes prudent when at "enterprise scale" (and utilising a hub-spoke topology) to restrict the ranges which spokes may utilise. Failing to do so has the potential for this to be used as an attack vector (both intentionally and unintentionally) to null-route traffic intended for on-premise (i.e. over ExpressRoute).
This policy provides a mechanism for preventing a VNET's address space from existing outside of ranges configured for a region, leveraging the name of the subscription to define the environment (e.g. PROD, DEV). This is ideal in situations where an enterprise has implemented sane IPAM, and in instances where the contents of a subscription is entirely under the control of the …
> Creation of Address Limitation Policy to Support Hub/Spoke

- Policies/Backup/vm-backup-without-tag/README.md
- Policies/Backup/vm-backup-without-tag/azurepolicy.json
- Policies/Backup/vm-backup-without-tag/azurepolicy.parameters.json
- Policies/Backup/vm-backup-without-tag/azurepolicy.rules.json
Policy to enable backup to an existing RSV in the same subscription. Option to skip vm's with spcified tag
> Enable backup of VMs to existing RSV in the same subscription

- Policies/Compute/allowed-disk-skus/azurepolicy.json
- Policies/Compute/allowed-disk-skus/azurepolicy.rules.json
Updating the resource type from 'disk' to 'disks' as per the documentation to fix the error displayed below:
Status Message: The policy definition '[Custom] Allowed Disk Skus' rule is invalid. The resource type 'disk'
'Microsoft.Compute'. (Code:InvalidResourceTypeInPolicyAlias)
> Disk SKU policy update

- Policies/Network/deny-private-endpoint-in-specific-subnets-based-on-naming-convention/azurepolicy.json
- Policies/Network/deny-private-endpoint-in-specific-subnets-based-on-naming-convention/azurepolicy.rules.json
Just a small improvement where the [last()](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-array#last) function is used instead of using indexing to get the subnet name.
> Replaced Private endpoint subnet index with last() function

- Policies/Compute/[Preview] Deploy AAD Login For Linux SSH extension on Linux virtual machines/README.md
- Policies/Compute/[Preview] Deploy AAD Login For Linux SSH extension on Linux virtual machines/deploy-aadlogin.json
- Policies/Compute/[Preview] Deploy AAD Login For Windows extension on Windows virtual machines/README.md
- Policies/Compute/[Preview] Deploy AAD Login For Windows extension on Windows virtual machines/deploy-aadlogin.json
This policy deploys AAD login for Linux SSH extension on Linux virtual machines and sets the VM with MSI.
This policy deploys AAD login for Windows extension on Windows virtual machines and sets the VM with MSI. This will join the Server as a device to AAD tenant.
> deploy aadlogin ext for vm servers

- README.md
Fixes grammar in the main README.md file.
> Main readme: Use "wary" instead of "weary"

- Policies/Network/deny-expressroute-authorization-key/azurepolicy.json
- Policies/Network/deny-expressroute-authorization-key/azurepolicy.parameters.json
- Policies/Network/deny-expressroute-authorization-key/azurepolicy.rules.json
Adding Azure policy to audit/deny the creation of authorization keys for ExpressRoute.
Authorization keys for ExpressRoute is used to enable cross-subscription/tenant network connectivity.
The process for generating these keys should be through a process owned by the network team.
> Adding Azure Policy for denying/auditing authorizations keys for ExpressRoute.

- Policies/Network/deny-vnet-subnet-serviceendpoints/azurepolicy.json
- Policies/Network/deny-vnet-subnet-serviceendpoints/azurepolicy.parameters.json
- Policies/Network/deny-vnet-subnet-serviceendpoints/azurepolicy.rules.json
Adding Azure Policy to deny/audit Service endpoints on subnets.
-----------
Service endpoints on subnets allows resources to bypass virtual network appliances implemented and other network security features. Service endpoint enablement is a process which should be owned by the network team and have limited use.
> Adding azure policy for auditing/denying service endpoints on subnets.

- Policies/Network/enforce_vnet_dns_servers/azurepolicy.json
a bugfix to address an edge-case that was discovered - supplying an empty array in the arm/bicep template for dns servers caused the first "anyOf" check to pass, despite it being empty, so the policy failed to apply as intended.  
The fix forces the test to be against an array that has something (anything!) in it, so that the test then moves on to the second part to test against the allowed list.
> Bugfix enforce_vnet_dns_servers edge-case of empty array

- Policies/SQL/audit-secure-transport-mysql-flexible/README.md
- Policies/SQL/audit-secure-transport-mysql-flexible/azurepolicy.json
- Policies/SQL/audit-secure-transport-mysql-flexible/azurepolicy.parameters.json
- Policies/SQL/audit-secure-transport-mysql-flexible/azurepolicy.rules.json
The buildin SSL policy only for Azure MySQL single server and is on the [retirement path](https://go.microsoft.com/fwlink/?linkid=2216041)
I created this policty for the new Azure MySQL flexible server.
> Added Require Secure Transport policy for Azure MySQL flexible servers

- Policies/Network/deny-nics-joining-asg-outside-of-same-resource-group/README.md
- Policies/Network/deny-nics-joining-asg-outside-of-same-resource-group/azurepolicy.json
- Policies/Network/deny-nics-joining-asg-outside-of-same-resource-group/azurepolicy.parameters.json
- Policies/Network/deny-nics-joining-asg-outside-of-same-resource-group/azurepolicy.rules.json
New Policy: Deny Network Interface from joining an Application Security Group (ASG) if it is in a different Resource Group
In some or most scenarios, ASGs live within the same Resource Group where VMs (Network Interface) is deployed. If a VM NIC is allowed to join an ASG from another Resource Group, it can leverage the NSG rules that are allowed for the other ASG, which grants it network access to other resources it shouldn't. This policy ensures that a VM can only use an ASG within the same Resource Group.
> New Policy: Deny Network Interface from joining an Application Security Group (ASG) if it is in a different Resource Group

- Policies/Network/deny-azurefirewallpolicy-rule-nat-type/azurepolicy.json
- Policies/Network/deny-azurefirewallpolicy-rule-nat-type/azurepolicy.parameters.json
- Policies/Network/deny-azurefirewallpolicy-rule-nat-type/azurepolicy.rules.json
- Policies/Network/deny-azurefirewallpolicy-rulecollectiongroup-nat-type/azurepolicy.json
- Policies/Network/deny-azurefirewallpolicy-rulecollectiongroup-nat-type/azurepolicy.parameters.json
- Policies/Network/deny-azurefirewallpolicy-rulecollectiongroup-nat-type/azurepolicy.rules.json
Adding Azure Policy to audit/deny NAT rule / rule collection for Azure Firewall Policy.
The NAT rule allows the Azure firewall to act as an Ingress in Azure.
Ingress through Azure should be monitored and managed by the organizations network team and follow the correct procedure to allow inbound traffic through NAT rules.
> Adding Azure Firewall NAT Azure Policies

- Policies/SQL/require-sql-server-vm-auto-backup/azurepolicy.json
- Policies/SQL/require-sql-server-vm-auto-backup/azurepolicy.parameters.json
- Policies/SQL/require-sql-server-vm-auto-patching/azurepolicy.json
- Policies/SQL/require-sql-server-vm-auto-patching/azurepolicy.parameters.json
- Policies/SQL/require-sql-server-vm-key-vault-integration/azurepolicy.json
- Policies/SQL/require-sql-server-vm-key-vault-integration/azurepolicy.parameters.json
- Policies/SQL/require-sql-server-vm-sql-connectivity/azurepolicy.json
- Policies/SQL/require-sql-server-vm-sql-connectivity/azurepolicy.parameters.json
Azure Policies
1. Require Key Vault Integration on SQL Server VM instances as a precursor to enabling Transparent Data Encryption (TDE).
2. Require Auto Patching so that the SQL Server VM can be up-to-date on the latest software and OS version.
3. Require Auto Backup so that the SQL Server VM can have its contents backed up on an Azure Storage Account Container.
4. Require SQL Connectivity setting so that users can toggle how the SQL Server VM accepts connections (Private, Public, Local).
> Adding 4 new Azure Policies for SQL Server VMs

- Policies/SQL/deploy-sql-database-shortterm-backup-retention-policy/azurepolicy.json
- Policies/SQL/deploy-sql-database-shortterm-backup-retention-policy/azurepolicy.parameters.json
- Policies/SQL/deploy-sql-database-shortterm-backup-retention-policy/azurepolicy.rules.json
Adding Azure Policy for Azure SQL Databases to deploy short-term backup retention policy if it does not exist.
Short-term retention policy is used to address point-in-time retention ability for near-term recovery of Azure SQL databases. It can be set to a number between 7-35 days for this retention policy. The default backup retention period under this policy is 7 days but it varies depending upon your pricing tier.
https://learn.microsoft.com/en-us/azure/azure-sql/database/temporal-tables-retention-policy?view=azuresql
> New sql database policy shortterm backup retention policy

- Policies/Compute/vm-extension-vmaccess/README.md
- Policies/Compute/vm-extension-vmaccess/azurepolicy.json
- Policies/Compute/vm-extension-vmaccess/azurepolicy.parameters.json
- Policies/Compute/vm-extension-vmaccess/azurepolicy.rules.json
This Azure policy blocks/audits the usage of the VM Extension called "VMAccessForLinux".
VMAccessForLinux allows the user of the VM to reset the ssh key/password for an existing user or create a new user with a password/ssh key with sudo rights.
The process of reseting the password for users or generating a new user should be monitored and follow a defined process to avoid accidental/intentional elevation of rights in the operating system.
> Adding Azure Policy for VMAccessForLinux vm extension.

- Policies/Compute/not-allowed-vmextension/azurepolicy.json
- Policies/Compute/not-allowed-vmextension/azurepolicy.parameters.json
- Policies/Compute/not-allowed-vmextension/azurepolicy.rules.json
Parameterized the effect as well as added support to block Defender for Endpoint (MDE.Windows / MDE.Linux) extension, if you for example want to run Defender for Servers without enabling MDE
> Parameterized effect and added support for MDE ext

- Policies/Monitoring/Diag2LAW/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace.json
- Policies/Monitoring/Diag2LAW/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace.parameters.json
- Policies/Monitoring/Diag2LAW/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace.rules.json
Deploys the diagnostic settings for Managed HSM Key Vaults to stream to a Log Analytics workspace when any Managed HSM Key Vault which is missing this diagnostic settings is created or updated. The policy will set the diagnostic with all metrics and category enabled.
> Deploy diag settings for MHSM to LAW

- Policies/APIManagement/Audit - Sample Products should be removed from API Management/Audit - Sample Products should be removed from API Management.json
- Policies/APIManagement/Audit - Sample Products should be removed from API Management/Audit - Sample Products should be removed from API Management.parameters.json
- Policies/APIManagement/Audit - Sample Products should be removed from API Management/Audit - Sample Products should be removed from API Management.rules.json
- Policies/APIManagement/Deny - Enforcing Internal VPN/Deny - Enforcing Internal VPN.json
- Policies/APIManagement/Deny - Enforcing Internal VPN/Deny - Enforcing Internal VPN.parameters.json
- Policies/APIManagement/Deny - Enforcing Internal VPN/Deny - Enforcing Internal VPN.rules.json
- Policies/Monitoring/Diag2LAW/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace.json
- Policies/Monitoring/Diag2LAW/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace.parameters.json
- Policies/Monitoring/Diag2LAW/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace.rules.json
The first policy is to audit because API Management includes two sample products 'Starter' and 'Unlimited'. Accidentally adding APIs to these sample products may expose APIs more than intended.
The next policy enforces the API Manager resource to be deployed in an Internal Virtual Private Network. No Public EndPoint, no External VPN.
> 2 policies for APIM audit sample products and deny external VPN

- Policies/Authorization/Deny policy exemption with an expiration date greater than given days/Deny policy exemption with an expiration date greater than given days.json
- Policies/Authorization/Deny policy exemption with an expiration date greater than given days/Deny policy exemption with an expiration date greater than given days.parameters.json
- Policies/Authorization/Deny policy exemption with an expiration date greater than given days/Deny policy exemption with an expiration date greater than given days.rules.json
- Policies/Authorization/Deny policy exemption without description/Deny policy exemption without description.json
- Policies/Authorization/Deny policy exemption without description/Deny policy exemption without description.parameters.json
- Policies/Authorization/Deny policy exemption without description/Deny policy exemption without description.rules.json
- Policies/Authorization/Deny policy exemption without expiration date/Deny policy exemption without expiration date.json
- Policies/Authorization/Deny policy exemption without expiration date/Deny policy exemption without expiration date.parameters.json
- Policies/Authorization/Deny policy exemption without expiration date/Deny policy exemption without expiration date.rules.json
- Policies/Authorization/Deny policy exemption without given info/Deny policy exemption without given info.json
- Policies/Authorization/Deny policy exemption without given info/Deny policy exemption without given info.parameters.json
- Policies/Authorization/Deny policy exemption without given info/Deny policy exemption without given info.rules.json
4 different policies to control that a policy exemption has the detailed described in the policies otherwise it will deny the creation.
Cannot create a policy exemption without:
- description
- expiration date
- expiration date cannot be greater than X-days
And 1 policy to combine the above 3 points.
> Added policies to control policy exemption details

- Policies/Compute/Deny data access authentication mode/Deny data access authentication mode.json
- Policies/Compute/Deny data access authentication mode/Deny data access authentication mode.parameters.json
- Policies/Compute/Deny data access authentication mode/Deny data access authentication mode.rules.json
Disable data access authentication mode to restrict access to export the disk. https://learn.microsoft.com/en-us/azure/virtual-machines/windows/download-vhd?tabs=azure-portal#secure-downloads-and-uploads-with-azure-ad
A supplement to export data disks but in some cases you might not want to have RBAC enabled for disk export.
> Deny data access auth mode

- Policies/EventHub/Deny - Configure Event Hubs to allow only certain SKUs/azurepolicy.json
- Policies/EventHub/Deny - Configure Event Hubs to allow only certain SKUs/azurepolicy.parameters.json
- Policies/EventHub/Deny - Configure Event Hubs to allow only certain SKUs/azurepolicy.rules.json
- Policies/EventHub/Deny - Configure Event Hubs to disable public network access/azurepolicy.json
- Policies/EventHub/Deny - Configure Event Hubs to disable public network access/azurepolicy.parameters.json
- Policies/EventHub/Deny - Configure Event Hubs to disable public network access/azurepolicy.rules.json
- Policies/EventHub/Deny - Configure Event Hubs to use availability zones/azurepolicy.json
- Policies/EventHub/Deny - Configure Event Hubs to use availability zones/azurepolicy.parameters.json
- Policies/EventHub/Deny - Configure Event Hubs to use availability zones/azurepolicy.rules.json
Adding 3 policies to deny wrong configuration on Event Hubs for different scenarios.
See policy descriptions for further info.
> Deny on Configuring Event Hubs

- Policies/ResourceGroup/Deploy Resource Lock on RGs - tag exclusion/azurepolicy.json
- Policies/ResourceGroup/Deploy Resource Lock on RGs - tag exclusion/azurepolicy.parameters.json
- Policies/ResourceGroup/Deploy Resource Lock on RGs - tag exclusion/azurepolicy.rules.json
Automatically deploys a resource lock to resources that are not in the dv environment to prevent accidental deletion.
> Deploy Resource Lock on RGs - tag exclusion

- Policies/Monitoring/deploy-diagnostic-setting-for-activity-log-storage-account/azurepolicy.json
- Policies/Monitoring/deploy-diagnostic-setting-for-activity-log-storage-account/azurepolicy.parameters.json
- Policies/Monitoring/deploy-diagnostic-setting-for-activity-log-storage-account/azurepolicy.rules.json
Added Policy definition 'deploy-diagnostic-setting-for-activity-log-storage-account' to complement existing policies that target Log Analytics and Event Hub.
> deploy-diagnostic-setting-for-activity-log-storage-account

- Policies/Bastion/deny-shared-links/azurepolicy.json
- Policies/Bastion/deny-shared-links/azurepolicy.parameters.json
- Policies/Bastion/deny-shared-links/azurepolicy.rules.json
The Bastion Shareable Link feature lets users connect to a target resource (virtual machine or virtual machine scale set) using Azure Bastion without accessing the Azure portal.
If you don't want to expose this feature, this policy will prevent enabling the setting.
> Add deny-bastion-shared-links Policy definition

- Policies/CognitiveServices/allowed-cognitive-types/azurepolicy.json
- Policies/CognitiveServices/allowed-cognitive-types/azurepolicy.parameters.json
- Policies/CognitiveServices/allowed-cognitive-types/azurepolicy.rules.json
- Policies/CognitiveServices/allowed-openai-models/azurepolicy.json
- Policies/CognitiveServices/allowed-openai-models/azurepolicy.parameters.json
- Policies/CognitiveServices/allowed-openai-models/azurepolicy.rules.json
This PR adds the following policies:
Only approved kinds Cognitive Services resources
Permit only approved OpenAI models
> Permit Cognitive Service Kinds and OpenAI Models

- Policies/Storage/Restrict cloud shell storage account creation/azurepolicy.json
- Policies/Storage/Restrict cloud shell storage account creation/azurepolicy.parameters.json
- Policies/Storage/Restrict cloud shell storage account creation/azurepolicy.rules.json
Storage accounts that you create in Cloud Shell are tagged with ms-resource-usage:azure-cloud-shell. If you want to disallow users from creating storage accounts in Cloud Shell - which you have several good security reasons for - create an Azure resource policy for tags that is triggered by this specific tag. https://learn.microsoft.com/en-us/azure/cloud-shell/persisting-shell-storage#restrict-resource-creation-with-an-azure-resource-policy
> Restrict cloud shell storage account creation

- Policies/Compute/allowed-snapshots-diskstates/azurepolicy.json
- Policies/Compute/allowed-snapshots-diskstates/azurepolicy.parameters.json
- Policies/Compute/allowed-snapshots-diskstates/azurepolicy.rules.json
New Azure policy to control the disk state for Azure Snapshots.
Disallowing the diskState to be set to, for example ActiveSAS or ActiveSASFrozen will block the possibility of exporting an Azure Snapshots using SAS tokens.
> adding new azure policy for Azure Snapshots - Diskstate

- policyDefinitions/Storage/audit-storageaccounts-should-have-lifecycle-policy-enabled/azurepolicy.json
- policyDefinitions/Storage/audit-storageaccounts-should-have-lifecycle-policy-enabled/azurepolicy.parameters.json
- policyDefinitions/Storage/audit-storageaccounts-should-have-lifecycle-policy-enabled/azurepolicy.rules.json
Policy that Audits storage accounts that have no lifecycle policy enabled
> Audit -  StorageAccounts Should Have Lifecycle Policy Enabled

- policyDefinitions/Compute/deploy-windows-vm-app/azurepolicy.json
As the original if ("b83d392d-3a11-41ac-bf39-c6ee381b9255") was used for these community policies:
- policyDefinitions/Compute/deploy-linux-vm-app
- policyDefinitions/Compute/deploy-windows-vm-app
> Fix: Create a unique policy id

- policyDefinitions/SQL/configure-azure-sql-db-to-use-tls-1.2/azurepolicy.json
As the original if ("73290fa2-dfa7-4bbb-945d-a5e23b75df2c") was used for these policies (community and built-in):
- policyDefinitions/SQL/configure-azure-sql-db-to-use-tls-1.2
- /providers/Microsoft.Authorization/policyDefinitions/73290fa2-dfa7-4bbb-945d-a5e23b75df2c
> Fix: Create a unique SQL policy id

- policyDefinitions/Network/deploy-private-endpoint-private-dns-zone-link/azurepolicy.json
- policyDefinitions/Network/deploy-private-endpoint-private-dns-zone-link/azurepolicy.rules.json
fix for [#403](https://github.com/Azure/Community-Policy/issues/403)
blob_secondary domain
> fix(deploy-private-endpoint-private-dns-zone-link): typo in

- policySetDefinitions/regulatorycompliance-nzism/README.md
Updated documentation to reflect new file names
> Updated readme

- policyDefinitions/Network/vnet-peering-deny-removal/azurepolicy.json
- policyDefinitions/Network/vnet-peering-deny-removal/azurepolicy.parameters.json
- policyDefinitions/Network/vnet-peering-deny-removal/azurepolicy.rules.json
Added policy definition for Deny VNet peering removal
> Add policy to deny vnet peering removal

- policyDefinitions/Network/address-space-must-be-pre-allocated-for-region/azurepolicy.json
- policyDefinitions/Network/address-space-must-be-pre-allocated-for-region/azurepolicy.parameters.json
- policyDefinitions/Network/address-space-must-be-pre-allocated-for-region/azurepolicy.rules.json
- Add "defaultValue" to defined "(optional)" parameter so it is not set as a required parameter when creating the Policy Assignment. 
- Add string() function to the remoteVirtualNetwork.id split to allow for it to resolve without errors.
> BugFix: Address space must be pre-allocated for region

- policySetDefinitions/regulatorycompliance-nzism/README.md
Updating the deployment instructions in prep for v3.7 which will be coming soon
> Updated nzism deployment cloud shell instructions

- policyDefinitions/App Service/function-apps-should-have-ftp-basic-auth-disabled/azurepolicy.json
- policyDefinitions/App Service/function-apps-should-have-ftp-basic-auth-disabled/azurepolicy.parameters.json
- policyDefinitions/App Service/function-apps-should-have-ftp-basic-auth-disabled/azurepolicy.rules.json
- *Name*: Function apps should have basic local authentication methods disabled for FTP deployments
- *Description*: Disabling local authentication methods for FTP deployments improves security by ensuring that Function apps exclusively require Microsoft Entra identities for authentication. Learn more at: https://aka.ms/app-service-disable-basic-auth.
- *Category*: App Service
Audit if basic local authentication methods for FTP deployments is disabled
App Service provides basic authentication for FTP and WebDeploy clients to connect to it by using [deployment credentials](https://learn.microsoft.com/en-us/azure/app-service/deploy-configure-credentials). 
These APIs are great for browsing your site’s file system, …
> New Policy (Azure Function App): Function apps should have basic local authentication methods disabled for FTP deployments

- policyDefinitions/SQL/postgresql-flexible-servers-should-log-connections/azurepolicy.json
- policyDefinitions/SQL/postgresql-flexible-servers-should-log-connections/azurepolicy.parameters.json
- policyDefinitions/SQL/postgresql-flexible-servers-should-log-connections/azurepolicy.rules.json
- *Name*: PostgreSQL flexible servers should log connections
- *Description*: This policy helps audit any PostgreSQL databases in your environment without log_connections setting enabled
This policy helps audit any PostgreSQL databases in your environment without log_connections setting enabled
Enabling log_connections helps PostgreSQL Database to log attempted connection to the server, as well as successful completion of client authentication.
> New Policy (Azure Database for PostgreSQL flexible servers): PostgreSQL flexible servers should log connections

- policyDefinitions/SQL/postgresql-flexible-servers-should-log-checkpoints/azurepolicy.json
- policyDefinitions/SQL/postgresql-flexible-servers-should-log-checkpoints/azurepolicy.parameters.json
- policyDefinitions/SQL/postgresql-flexible-servers-should-log-checkpoints/azurepolicy.rules.json
- *Name*: PostgreSQL flexible servers should log checkpoints
- *Description*: This policy helps audit any PostgreSQL databases in your environment without log_checkpoints setting enabled
This policy helps audit any PostgreSQL databases in your environment without log_checkpoints setting enabled
Enabling log_checkpoints helps the PostgreSQL Database to Log each checkpoint in turn generates query and error logs. However, access to transaction logs is not supported.
Query and error logs can be used to identify, troubleshoot, and repair configuration errors and sub-optimal performance.
> New Policy (Azure Database for PostgreSQL flexible servers): PostgreSQL flexible servers should log checkpoints

- policyDefinitions/SQL/postgresql-flexible-servers-should-enforce-ssl-connections/azurepolicy.json
- policyDefinitions/SQL/postgresql-flexible-servers-should-enforce-ssl-connections/azurepolicy.parameters.json
- policyDefinitions/SQL/postgresql-flexible-servers-should-enforce-ssl-connections/azurepolicy.rules.json
- *Name*: PostgreSQL flexible servers should enforce SSL connections
- *Description*: Azure Database for PostgreSQL supports connecting your Azure Database for PostgreSQL server to client applications using Secure Sockets Layer (SSL). Enforcing SSL connections between your database server and your client applications helps protect against 'man in the middle' attacks by encrypting the data stream between the server and your application. This configuration enforces SSL for accessing your database server
Audit if PostgreSQL flexible servers enforce SSL connections
Azure Database for PostgreSQL supports connecting your Azure Database for PostgreSQL server to client applications using Secure Sockets Layer (SSL). Enforcing …
> New Policy (Azure Database for PostgreSQL flexible servers): PostgreSQL flexible servers should enforce SSL connections

- policyDefinitions/Kubernetes/ensure-ephemeral-disks-are-used-for-os-disks-on-agent-pools/azurepolicy.json
- policyDefinitions/Kubernetes/ensure-ephemeral-disks-are-used-for-os-disks-on-agent-pools/azurepolicy.parameters.json
- policyDefinitions/Kubernetes/ensure-ephemeral-disks-are-used-for-os-disks-on-agent-pools/azurepolicy.rules.json
- *Name*: Ensure ephemeral disks are used for OS disks on Agent Pools
- *Description*: Ephemeral OS disks are created on the local virtual machine (VM) storage and not saved to the remote Azure Storage, as when using managed OS disks
- *Supported effect(s)*: Deny, Audit, Disabled
Ensure ephemeral disks are used for OS disks on Agent Pools
Ephemeral OS disks are created on the local virtual machine (VM) storage and not saved to the remote Azure Storage, as when using managed OS disks. For more information on the performance of a managed disk, see [Disk allocation and performance](https://learn.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview). Ephemeral OS disks work well for stateless workloads, where applications are tolerant of individual VM …
> New Policy (Azure Kubernetes Services): Ensure ephemeral disks are used for OS disks on Agent Pools

- policyDefinitions/Kubernetes/ensure-ephemeral-disks-are-used-for-os-disks-on-agent-pool-profiles/azurepolicy.json
- policyDefinitions/Kubernetes/ensure-ephemeral-disks-are-used-for-os-disks-on-agent-pool-profiles/azurepolicy.parameters.json
- policyDefinitions/Kubernetes/ensure-ephemeral-disks-are-used-for-os-disks-on-agent-pool-profiles/azurepolicy.rules.json
- *Name*: Ensure ephemeral disks are used for OS disks on Agent Pool Profiles
- *Description*: Ephemeral OS disks are created on the local virtual machine (VM) storage and not saved to the remote Azure Storage, as when using managed OS disks
- *Supported effect(s)*: Deny, Audit, Disabled
Ensure ephemeral disks are used for OS disks on Agent Pool Profiles
Ephemeral OS disks are created on the local virtual machine (VM) storage and not saved to the remote Azure Storage, as when using managed OS disks. For more information on the performance of a managed disk, see [Disk allocation and performance](https://learn.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview). Ephemeral OS disks work well for stateless workloads, where applications are tolerant of …
> New Policy (Azure Kubernetes Services): Ensure ephemeral disks are used for OS disks on Agent Pool Profiles

- policyDefinitions/App Service/web-apps-should-have-ftp-basic-auth-disabled/azurepolicy.json
- policyDefinitions/App Service/web-apps-should-have-ftp-basic-auth-disabled/azurepolicy.parameters.json
- policyDefinitions/App Service/web-apps-should-have-ftp-basic-auth-disabled/azurepolicy.rules.json
- *Name*: Web App should have basic local authentication methods disabled for FTP deployments
- *Description*: Disabling local authentication methods for FTP deployments improves security by ensuring that Web apps exclusively require Microsoft Entra identities for authentication. Learn more at: https://aka.ms/app-service-disable-basic-auth.
- *Category*: App Service
Audit if basic local authentication methods for FTP deployments is disabled
App Service provides basic authentication for FTP and WebDeploy clients to connect to it by using [deployment credentials](https://learn.microsoft.com/en-us/azure/app-service/deploy-configure-credentials). 
These APIs are great for browsing your site’s file system, uploading …
> New Policy (Azure Web Apps): Web apps should have basic local authentication methods disabled for FTP deployments

- policyDefinitions/App Service/app-service-apps-should-use-the-latest-tls-version-for-scm-connections/azurepolicy.json
- policyDefinitions/App Service/app-service-apps-should-use-the-latest-tls-version-for-scm-connections/azurepolicy.parameters.json
- policyDefinitions/App Service/app-service-apps-should-use-the-latest-tls-version-for-scm-connections/azurepolicy.rules.json
- *Name*: App Service apps should use the latest TLS version for SCM connections
- *Description*: This policy helps audit any Azure Service apps should use the latest TLS version for SCM connections.
This policy helps audit any Azure Service apps should use the latest TLS version for SCM connections
Periodically, newer versions are released for TLS either due to security flaws, include additional functionality, and enhance speed. Upgrade to the latest TLS version for Function apps to take advantage of security fixes, if any, and/or new functionalities of the latest version.
> New Policy (Azure App Services): App Service apps should use the latest TLS version for SCM connections

- policyDefinitions/Monitoring/deploy-diagnostic-settings-for-web-slots-to-log-analytics-workspace/azurepolicy.json
- policyDefinitions/Monitoring/deploy-diagnostic-settings-for-web-slots-to-log-analytics-workspace/azurepolicy.parameters.json
- policyDefinitions/Monitoring/deploy-diagnostic-settings-for-web-slots-to-log-analytics-workspace/azurepolicy.rules.json
This policy is to enable Diagnostic Settings on Web Slots
> New diagnostic policy definition

- policyDefinitions/App Service/deploy-app-private-endpoint-private-dns-zone-link-domainbased/azurepolicy.json
- policyDefinitions/App Service/deploy-app-private-endpoint-private-dns-zone-link-domainbased/azurepolicy.parameters.json
- policyDefinitions/App Service/deploy-app-private-endpoint-private-dns-zone-link-domainbased/azurepolicy.rules.json
The builtin policy [Configure App Service apps to use private DNS zones](https://www.azadvertizer.net/azpolicyadvertizer/b318f84a-b872-429b-ac6d-a01b96814452.html) does not evaluate the domain suffix used by the App Service app (azurewebsites.net versus appserviceenvironment.net).
I've created a custom policy as an improvement since it uses ARM template functions to determine the domain suffix in the defaultHostname property of the App Service App, and then determines which of the two private dns zones to use (given by the input parameters).
> Add policy to configure domain-based dns zone configuration on App Service Private Endpoints

- policyDefinitions/Compute/deploy-windows-vm-app/azurepolicy.json
```json
{
"field": "Microsoft.Compute/virtualMachines/storageProfile.osDisk.osType",
"equals": "Windows"
}
``` 
The issue is that the create payload for VMs does not include the property osType, which is evaluated in the "if" condition the Policy, which makes Policy see the resource as not applicable for a deployment until later.
The solution is to check on the image reference, and this PR shows 1 way of doing exactly that. 
The policy works fine "as is" for manually remediating and will also be triggered by any change to the VM (for example a resize).
> Policy does not remediate automatically on deployment of Windows VM

- policyDefinitions/Network/deploy-a-traffic-analytics-enabled-flow-log-resource-with-target-virtual-network/azurepolicy.json
- policyDefinitions/Network/deploy-a-traffic-analytics-enabled-flow-log-resource-with-target-virtual-network/azurepolicy.parameters.json
- policyDefinitions/Network/deploy-a-traffic-analytics-enabled-flow-log-resource-with-target-virtual-network/azurepolicy.rules.json
There's a built-in Policy Definition 'Deploy a Flow Log resource with target virtual network' that can enable Flow Logging for virtual networks to a storage account. However, it doesn't support logging to a Log Analytics workspace.
There's a Community Policy 'Deploy a traffic analytics enabled flow log resource with target tagged network security group' that supports this, but only for NSG Flow Logging, not virtual network Flow Logging.
I combined built-in and Community Policy to support virtual network Flow Logging to a Log Analytics workspace.
> Deploy a Traffic Analytics enabled Flow Log resource with target virtual network

- Scripts/Format-PolicyDefinition.ps1
This pull request includes a significant change to the `Format-PolicyDefinition` function in the `Scripts/Format-PolicyDefinition.ps1` file. The primary focus is on improving error handling and ensuring the JSON content is correctly parsed.
Key changes include:
* Added a try-catch block to handle exceptions when converting JSON content, ensuring any errors are caught and their messages are thrown. (`Scripts/Format-PolicyDefinition.ps1`)
* Restored the use of `ConvertFrom-Json` with `-AsHashtable` and `-Depth 100` to handle the JSON conversion more robustly. (`Scripts/Format-PolicyDefinition.ps1`)table, we cannot remove keys one by one, causing the script to fail.
> FIX: Ensure '$definition' is Hashtable in 'Format-PolicyDefinition'

- policyDefinitions/Kubernetes/append-aks-api-ip-restrictions/azurepolicy.json
- policyDefinitions/Kubernetes/append-aks-api-ip-restrictions/azurepolicy.parameters.json
- policyDefinitions/Kubernetes/append-aks-api-ip-restrictions/azurepolicy.rules.json
This PR addresses the issue "Append AKS API IP Restrictions is not working" in the policy file policyDefinitions/Kubernetes/append-aks-api-ip-restrictions. 
The proposed changes fix the handling of authorizedIPRanges to ensure proper IP restrictions when creating and updating resources.
**When creating the resource:**
If authorizedIPRanges is not added, the policy appends the required IPs automatically and allows resource creation.
If authorizedIPRanges is added but some required IPs are missing, the policy blocks resource creation.
If all required IPs are correctly added, the policy allows the resource creation.
**After the resource is created:**
Adding new IPs is blocked by the policy.
Removing IPs is blocked by the policy.
If the same number of IPs is present but one is different, the …
> Fix: Append AKS API IP Restrictions is not working (#465)

- .github/workflows/confirm-policy-definition-no-built-in-conflicts.yaml
#393 
Updated Built-In Name / GUID validation check to use public resource that does not require us to maintain an authorization token like the Github APIs would require. 
Also updated dependencies to the latest versions.
> Validate in the pipeline that policy id is not equal to any built-in policies

- policyDefinitions/SQL/audit-allow-azure-services-and-resources-to-access-this-server/azurepolicy.json
- policyDefinitions/SQL/audit-allow-azure-services-and-resources-to-access-this-server/azurepolicy.parameters.json
- policyDefinitions/SQL/audit-allow-azure-services-and-resources-to-access-this-server/azurepolicy.rules.json
Hi!
Added an audit policy to more easily audit instances where SQL servers are configured to allow incoming network connections from other services within the same tenant or any Azure tenant. This configuration can be unintended, and one may not always realize the consequence of such a configuration.
> Add audit policy for resource access from other services and tenants

- .github/workflows/confirm-policy-definition-no-built-in-conflicts.yaml
#475 
Add trim delete to file path, removing trailing \ when present. 
- Tests Ran:
- file name including appended '\\' `Result: the trailing backslash is removed`
- file name not including '\\' `Result: no changes made to file path`  
- file name actually includes a trailing '\\' (actually part of the file name) `Result: the check will fail with an invalid file path error. `
> Fix for trailing backslash validation issue. 

- policyDefinitions/Authorization/deny-custom-roles-with-exclusionlist/azurepolicy.json
- policyDefinitions/Authorization/deny-custom-roles-with-exclusionlist/azurepolicy.parameters.json
- policyDefinitions/Authorization/deny-custom-roles-with-exclusionlist/azurepolicy.rules.json
Adding a new Azure Policy Defintion to support the possibility to audit/deny Custom Roles with an exclusion list.
> Adding new policy definition to handle custom roles with exclusionlist

- policyDefinitions/Compute/deploy-qualys-agent-to-windows-vms/azurepolicy.json
- policyDefinitions/Compute/deploy-qualys-agent-to-windows-vms/azurepolicy.parameters.json
- policyDefinitions/Compute/deploy-qualys-agent-to-windows-vms/azurepolicy.rules.json
The Microsoft Defender for Cloud Enable vulnerability scanning with the integrated Qualys scanner has been deprecated. So, I created this policy to deploy the Qualys Agent (BYOL) on Windows VMs.
> Add deploy-qualys-agent-to-windows-vms policy that deploy BYOL Qualys agent to Windows VMs

- .github/workflows/confirm-policy-definition-no-built-in-conflicts.yaml
- Policies/Storage/enforce-or-extend-storage-account-iprules-if-tag-match/azurepolicy.json
#491 
Root Cause:
I was able to find the source file we are getting from https://www.azadvertizer.net is now large enough that it is being compressed to binary and therefore was failing to be parsed by the JSON parser in bash.
Solution:
Added the --compressed flag to the curl request to handle the compression of the file.
Extra Testing:
Validated the --compressed flag in curl would not throw an error when downloading an uncompressed file so this should not be a breaking change if we start receiving an uncompressed response from azadvertizer.net again. 
#477 
While in the code I also added the wording improvements to this script to remove the direct references to built-in definitions and to keep the responses more generic / inclusive of the fact that we can also match community policies …
> Unique ID GitHub Action - parsing failure fix and wording update

- README.md
The MicrosoftDocs/feedback repo is now read-only.
> Remove link to read-only repo

- policyDefinitions/Storage/enforce-or-extend-storage-account-iprules-if-tag-match/azurepolicy.json
- policyDefinitions/Storage/enforce-or-extend-storage-account-iprules-if-tag-match/azurepolicy.rules.json
removing incorrect character from the deployment template
the remediation has been tested and works on greenfield and brownfield
> removing incorrect character from the deployment template

- policyDefinitions/General/deny-fabric-capacity-creation/azurepolicy.json
- policyDefinitions/General/deny-fabric-capacity-creation/azurepolicy.parameters.json
- policyDefinitions/General/deny-fabric-capacity-creation/azurepolicy.rules.json
This PR introduces a simple "Deny-Resource" policy focused on Fabric Capacities. 
The policy is required for organisations which wants to govern the usage of Fabric within their own ecosystem, due to the implementation of capacities. 
The General category has been used as a catch-all, seeing as Fabric does not have a more specific one. 
The following scenarios has been tested.
> New Policy: Deny Fabric Capacity Creation

- .devcontainer/devcontainer.json
- policyDefinitions/Monitoring/log-analytics-workspace-require-daily-quota/azurepolicy.json
- policyDefinitions/Monitoring/log-analytics-workspace-require-daily-quota/azurepolicy.parameters.json
- policyDefinitions/Monitoring/log-analytics-workspace-require-daily-quota/azurepolicy.rules.json
This PR introduces a new (custom) policy definition that will deny a log analytics workspace resource being created without a daily quota property being set.
Log Analytics category is not valid in the tests, therefore I have used 'Monitoring' to align to the existing LAW definition about retention.
> New Policy Def: Deny Log Analytics Workspace without Daily Quota

- policyDefinitions/Network/allowed-pdns-zones/azurepolicy.json
- policyDefinitions/Network/allowed-pdns-zones/azurepolicy.parameters.json
- policyDefinitions/Network/allowed-pdns-zones/azurepolicy.rules.json
I've added this new Policy definition to cater for the scenario where Private DNS zones are not allowed to be deployed, except for a set of excluded zones (e.g. AKS private DNS zone).
I validated the policy by attempting to create a PDNS zone that is not in the list (blocked) and one that was in the list (allowed).
> New definition "Allowed Private DNS Zones"

- policyDefinitions/Tags/inherit-tag-from-subscription-to-resource-group/azurepolicy.json
- policyDefinitions/Tags/inherit-tag-from-subscription-to-resource-group/azurepolicy.parameters.json
- policyDefinitions/Tags/inherit-tag-from-subscription-to-resource-group/azurepolicy.rules.json
Introduce a policy definition that allows resource groups to inherit specified tags from their containing subscription when those tags are missing. 
Existing resource groups can be remediated through a task if necessary.
[x] Confirm-PolicyDefinitionIsValid returns valid
[x] Tested with new resource creation (modified)
[x] Tested with existing resource changes (modified)
> Add policy to inherit tags from subscription to resource group
