Azure/Community-Policy

Policies/Network/deny-vm-vmss-and-load-balancer-from-subnet/azurepolicy.json
Policies/Network/deny-vm-vmss-and-load-balancer-from-subnet/azurepolicy.parameters.json
Policies/Network/deny-vm-vmss-and-load-balancer-from-subnet/azurepolicy.rules.json

policy was blocking the deployment of load balancers that do not have frontend ip configurations. update to allow

Updated LB policy to allow for blank creations

---

Policies/Compute/allowed-disk-skus/azurepolicy.json
Policies/Compute/allowed-disk-skus/azurepolicy.parameters.json
Policies/Compute/allowed-disk-skus/azurepolicy.rules.json
Policies/Compute/blocked-disk-skus/azurepolicy.json
Policies/Compute/blocked-disk-skus/azurepolicy.parameters.json
Policies/Compute/blocked-disk-skus/azurepolicy.rules.json

Added a couple of managed disk policies to allow customers to block/allow disk skus

Allow/Block Managed Disk polcies for Sku

---

Policies/Kubernetes/allowed-host-paths/azurepolicy.json
Policies/Kubernetes/allowed-host-paths/azurepolicy.parameters.json
Policies/Kubernetes/allowed-users/azurepolicy.json
Policies/Kubernetes/allowed-users/azurepolicy.parameters.json
Policies/Kubernetes/fsgroup/azurepolicy.json
Policies/Kubernetes/fsgroup/azurepolicy.parameters.json
Policies/Kubernetes/selinux/azurepolicy.json
Policies/Kubernetes/selinux/azurepolicy.parameters.json
Policies/Kubernetes/selinux/azurepolicy.rules.json

Add object schema in Kubernetes PSP policies

Add object schema in Kubernetes PSP policies

---

Policies/SQL/audit-sql-server-private-endpoint/README.md
Policies/SQL/audit-sql-server-private-endpoint/azurepolicy.json
Policies/SQL/audit-sql-server-private-endpoint/azurepolicy.rules.json
Policies/SQL/audit-sql-server-public-network-access/README.md
Policies/SQL/audit-sql-server-public-network-access/azurepolicy.json
Policies/SQL/audit-sql-server-public-network-access/azurepolicy.rules.json

Update the display name and description for Public Network Access and Private Endpoint connection settings for Azure SQL Database

Azure SQL Server Policies for Private Links and Public Network Access

---

Policies/SQL/audit-sql-server-private-endpoint/azurepolicy.json
Policies/SQL/audit-sql-server-private-endpoint/azurepolicy.rules.json
Policies/SQL/audit-sql-server-public-network-access/azurepolicy.json
Policies/SQL/audit-sql-server-public-network-access/azurepolicy.rules.json

Modify the type property according to the changes in AzureUX-ARM repository.

Azure SQL DB - Private Endpoints and Public Network Access - Policy Update

---

Policies/Storage/deploy-storage-monitoring-log-analytics/README.md
Policies/Storage/deploy-storage-monitoring-log-analytics/azurepolicy.json
Policies/Storage/deploy-storage-monitoring-log-analytics/azurepolicy.parameters.json
Policies/Storage/deploy-storage-monitoring-log-analytics/azurepolicy.rules.json
Policies/Storage/deploy-storage-monitoring-log-analytics/blobservices/README.md
Policies/Storage/deploy-storage-monitoring-log-analytics/blobservices/azurepolicy.json
Policies/Storage/deploy-storage-monitoring-log-analytics/blobservices/azurepolicy.parameters.json
Policies/Storage/deploy-storage-monitoring-log-analytics/blobservices/azurepolicy.rules.json
Policies/Storage/deploy-storage-monitoring-log-analytics/fileservices/README.md
Policies/Storage/deploy-storage-monitoring-log-analytics/fileservices/azurepolicy.json
Policies/Storage/deploy-storage-monitoring-log-analytics/fileservices/azurepolicy.parameters.json
Policies/Storage/deploy-storage-monitoring-log-analytics/fileservices/azurepolicy.rules.json
Policies/Storage/deploy-storage-monitoring-log-analytics/queueservices/README.md
Policies/Storage/deploy-storage-monitoring-log-analytics/queueservices/azurepolicy.json
Policies/Storage/deploy-storage-monitoring-log-analytics/queueservices/azurepolicy.parameters.json
Policies/Storage/deploy-storage-monitoring-log-analytics/queueservices/azurepolicy.rules.json
Policies/Storage/deploy-storage-monitoring-log-analytics/storageaccounts/README.md
Policies/Storage/deploy-storage-monitoring-log-analytics/storageaccounts/azurepolicy.json
Policies/Storage/deploy-storage-monitoring-log-analytics/storageaccounts/azurepolicy.parameters.json
Policies/Storage/deploy-storage-monitoring-log-analytics/storageaccounts/azurepolicy.rules.json
Policies/Storage/deploy-storage-monitoring-log-analytics/tableservices/README.md
Policies/Storage/deploy-storage-monitoring-log-analytics/tableservices/azurepolicy.json
Policies/Storage/deploy-storage-monitoring-log-analytics/tableservices/azurepolicy.parameters.json
Policies/Storage/deploy-storage-monitoring-log-analytics/tableservices/azurepolicy.rules.json

Storage monitoring policies for Azure Storage Monitoring (preview) (ref <https://docs.microsoft.com/azure/storage/common/monitor-storage>). Includes policies and examples for single resources (*e.g.* blobServices, tableServices, fileServices, storageAccounts, etc.) and an overarching policy that enables storage monitoring for the parent storageAccounts resource and all of its proxy resources.

Azure Storage Monitoring Policies

---

Policies/SQL/deploy-sql-managedinstance-diag-loganalytics/README.md
Policies/SQL/deploy-sql-managedinstance-diag-loganalytics/azurepolicy.json
Policies/SQL/deploy-sql-managedinstance-diag-loganalytics/azurepolicy.parameters.json
Policies/SQL/deploy-sql-managedinstance-diag-loganalytics/azurepolicy.rules.json

adding azure policy to deploy Diagnostic Settings for Azure SQL MI databases to Log Analytics. 
There is no built-in policy for this.

added policy files and readme

---

Policies/Storage/deploy-storage-monitoring-log-analytics/README.md
Policies/Storage/deploy-storage-monitoring-log-analytics/blobservices/README.md
Policies/Storage/deploy-storage-monitoring-log-analytics/fileservices/README.md
Policies/Storage/deploy-storage-monitoring-log-analytics/queueservices/README.md
Policies/Storage/deploy-storage-monitoring-log-analytics/storageaccounts/README.md
Policies/Storage/deploy-storage-monitoring-log-analytics/tableservices/README.md

Update samples in Policies\Storage\deploy-storage-monitoring-log-analytics to point to the right URLs for raw github resources for all "Deploy to Azure" buttons and PowerShell/CLI commands.

Update deploy-storage-monitoring-log-analytics samples

---

Policies/Monitoring/deploy-oms-agent-based-on-region-linux/azurepolicy.json

Checking to see if the resource is in one of the target regions, not all of them?

Change equals to in

---

Policies/Security/deploy-vulnerablity-assesment-agent-for-custom-vm/README.md
Policies/Security/deploy-vulnerablity-assesment-agent-for-custom-vm/azurepolicy.json
Policies/Security/deploy-vulnerablity-assesment-agent-for-custom-vm/azurepolicy.parameters.json
Policies/Security/deploy-vulnerablity-assesment-agent-for-custom-vm/azurepolicy.rules.json

This policy automatically deploys Azure Security Center built-in vulnerability assessment Agent (Qualys) to Custom Virtual Machines built from Shared Gallery Image.

deploy-vulnerablity-assesment-agent-for-custom-vm

---

Policies/WebApps/deploy-webapp-force-https/azurepolicy.json
Policies/WebApps/deploy-webapp-force-https/azurepolicy.parameters.json
Policies/WebApps/deploy-webapp-force-https/azurepolicy.rules.json

Sets httosOnly to true on all Microsoft.Web/Sites

deploy-webapp-force-https

---

Policies/App Service/deploy-app-service-diag-log-analytics/README.md
Policies/App Service/deploy-app-service-diag-log-analytics/azurepolicy.json
Policies/App Service/deploy-app-service-diag-log-analytics/azurepolicy.parameters.json
Policies/App Service/deploy-app-service-diag-log-analytics/azurepolicy.rules.json

Added new policy for App Service that will configure diagnostics settings for Log Analytics.

Deploy sql database diag loganalytics

---

Policies/Compute/enforce-autoshutdown-vm/README.md
Policies/Compute/enforce-autoshutdown-vm/azurepolicy.parameters.json
Policies/Compute/enforce-autoshutdown-vm/azurepolicy.rules.json

it's a deployIfNotExists policy, see README

New policy to enable AutoShutdown VMs

---

Policies/Monitoring/audit-diagnostic-setting-for-wvd-applicationgroups-log-analytics/README.md
Policies/Monitoring/audit-diagnostic-setting-for-wvd-applicationgroups-log-analytics/azurepolicy.json
Policies/Monitoring/audit-diagnostic-setting-for-wvd-applicationgroups-log-analytics/azurepolicy.parameters.json
Policies/Monitoring/audit-diagnostic-setting-for-wvd-applicationgroups-log-analytics/azurepolicy.rules.json
Policies/Monitoring/audit-diagnostic-setting-for-wvd-hostpools-log-analytics/README.md
Policies/Monitoring/audit-diagnostic-setting-for-wvd-hostpools-log-analytics/azurepolicy.json
Policies/Monitoring/audit-diagnostic-setting-for-wvd-hostpools-log-analytics/azurepolicy.parameters.json
Policies/Monitoring/audit-diagnostic-setting-for-wvd-hostpools-log-analytics/azurepolicy.rules.json
Policies/Monitoring/audit-diagnostic-setting-for-wvd-workspaces-log-analytics/README.md
Policies/Monitoring/audit-diagnostic-setting-for-wvd-workspaces-log-analytics/azurepolicy.json
Policies/Monitoring/audit-diagnostic-setting-for-wvd-workspaces-log-analytics/azurepolicy.parameters.json
Policies/Monitoring/audit-diagnostic-setting-for-wvd-workspaces-log-analytics/azurepolicy.rules.json
Policies/Monitoring/deploy-diagnostic-setting-for-wvd-applicationgroups-log-analytics/README.md
Policies/Monitoring/deploy-diagnostic-setting-for-wvd-applicationgroups-log-analytics/azurepolicy.json
Policies/Monitoring/deploy-diagnostic-setting-for-wvd-applicationgroups-log-analytics/azurepolicy.parameters.json
Policies/Monitoring/deploy-diagnostic-setting-for-wvd-applicationgroups-log-analytics/azurepolicy.rules.json
Policies/Monitoring/deploy-diagnostic-setting-for-wvd-hostpools-log-analytics/README.md
Policies/Monitoring/deploy-diagnostic-setting-for-wvd-hostpools-log-analytics/azurepolicy.json
Policies/Monitoring/deploy-diagnostic-setting-for-wvd-hostpools-log-analytics/azurepolicy.parameters.json
Policies/Monitoring/deploy-diagnostic-setting-for-wvd-hostpools-log-analytics/azurepolicy.rules.json
Policies/Monitoring/deploy-diagnostic-setting-for-wvd-workspaces-log-analytics/README.md
Policies/Monitoring/deploy-diagnostic-setting-for-wvd-workspaces-log-analytics/azurepolicy.json
Policies/Monitoring/deploy-diagnostic-setting-for-wvd-workspaces-log-analytics/azurepolicy.parameters.json
Policies/Monitoring/deploy-diagnostic-setting-for-wvd-workspaces-log-analytics/azurepolicy.rules.json

Monitoring policies for WVD Services

Monitoring policies for WVD Services

---

Policies/Kubernetes/use-named-serviceaccount/constraint.yaml
Policies/Kubernetes/use-named-serviceaccount/examples-violations/violation.yaml
Policies/Kubernetes/use-named-serviceaccount/rego/src.rego
Policies/Kubernetes/use-named-serviceaccount/rego/src_test.rego
Policies/Kubernetes/use-named-serviceaccount/template.yaml

Update service accountpolicy to remove check for default serviceAccount name which is not needed and updated rego unit test as well

Update ServiceAccount Rego policy rego

---

Policies/Kubernetes/allowed-external-ips/azurepolicy.json
Policies/Kubernetes/allowed-external-ips/azurepolicy.parameters.json
Policies/Kubernetes/allowed-external-ips/azurepolicy.rules.json
Policies/Kubernetes/allowed-external-ips/constraint.yaml
Policies/Kubernetes/allowed-external-ips/examples-good/azurepolicy.assignment.parameters.json
Policies/Kubernetes/allowed-external-ips/examples-good/example_good.yaml
Policies/Kubernetes/allowed-external-ips/examples-violations/violation.yaml
Policies/Kubernetes/allowed-external-ips/rego/src.rego
Policies/Kubernetes/allowed-external-ips/rego/src_test.rego
Policies/Kubernetes/allowed-external-ips/template.yaml

Ref: https://github.com/Azure/AKS/issues/2012

Create Allowed External IPs PSP

---

Policies/Network/modify-routetable-nexthopvirtualappliance/README.md
Policies/Network/modify-routetable-nexthopvirtualappliance/azurepolicy.json
Policies/Network/modify-routetable-nexthopvirtualappliance/azurepolicy.parameters.json
Policies/Network/modify-routetable-nexthopvirtualappliance/azurepolicy.rules.json

Adds route with address prefix 0.0.0.0/0 pointing to the virtual appliance in case there is none.

Initial commit of modify-routetable-nexthopvirtualappliance

---

Policies/Network/modify-subnet-routetable/README.md
Policies/Network/modify-subnet-routetable/azurepolicy.json
Policies/Network/modify-subnet-routetable/azurepolicy.parameters.json
Policies/Network/modify-subnet-routetable/azurepolicy.rules.json

Adds the default route table to subnets. Other route tables are replaced with the default route table.

Initial commit of modify-subnet-routetable

---

Policies/SQL/depoly-sql-managedinstance-shortterm-backup-retention-policy/azurepolicy.json

commit new policy for sql managed instance for short term backup retention

Creating short term backup retention for sql managed instances policy

---

Policies/SQL/modify-sql-tls-version/README.md
Policies/SQL/modify-sql-tls-version/azurepolicy.json

new policy for modifying Azure SQL DB TLS settings

modify Azure SQL DB TLS

---

Policies/Compute/deploy-hybrid-benefit-windows/azurepolicy.json
Policies/Compute/deploy-hybrid-benefit-windows/azurepolicy.parameters.json
Policies/Compute/deploy-hybrid-benefit-windows/azurepolicy.rules.json

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/hybrid-use-benefit-licensing#ways-to-use-azure-hybrid-benefit-for-windows-server

Add DINE Policy which allows us to deploy Azure Hybrid Benefit config on existing VM's

---

Policies/Storage/Storage accounts should have minimal TLS version 1.2/azure-policy-definition-for-TLS-Audit.json

Existing file was not compatible with the Azure Policy Definition window. So stripped it with required fields. Made some small changes related to cases to make it compatible.

Made it compatible with Azure Policy Definition

---

Policies/Security/deployifnotexists-defender-for-servers/README.md
Policies/Security/deployifnotexists-defender-for-servers/azurepolicy.json
Policies/Security/deployifnotexists-defender-for-servers/azurepolicy.parameters.json
Policies/Security/deployifnotexists-defender-for-servers/azurepolicy.rules.json

[This policy will enable customers to deploy defender for VM using deploy if not exists rule]
This is my first commit, please provide feedback on the PR. Thanks

policy for defender for servers

---

Policies/KeyVault/deploy-soft-delete-and-purge-protection/azurepolicy.json

Changed DeployIfNotExists to deployIfNotExists as per documentation, Azure editor also complains about the casing

Update policy effect

---

Policies/EventHub/audit-minimum-tls-version/README.md
Policies/EventHub/audit-minimum-tls-version/azurepolicy.json
Policies/EventHub/audit-minimum-tls-version/azurepolicy.parameters.json
Policies/EventHub/audit-minimum-tls-version/azurepolicy.rules.json

Add policy to audit-minimum-tls-version on event hub resource

add audit-minimum-tls-version policy

---

Policies/MachineLearningServices/audit-compute-instance-os-version/README.md
Policies/MachineLearningServices/audit-compute-instance-os-version/azurepolicy.json
Policies/MachineLearningServices/audit-compute-instance-os-version/azurepolicy.parameters.json
Policies/MachineLearningServices/audit-compute-instance-os-version/azurepolicy.rules.json

Audit Azure Machine Learning Compute Instances with an outdated operating system

Azure Machine Learning policy for compute instance

---

Policies/Authorization/resource-lock-should-be-enabled/README.md
Policies/Authorization/resource-lock-should-be-enabled/azurepolicy.json
Policies/Authorization/resource-lock-should-be-enabled/azurepolicy.parameters.json
Policies/Authorization/resource-lock-should-be-enabled/azurepolicy.rules.json

- Complete walk-through in the following Blog post [Compliance and delegation of Azure Locks through Azure Policy](https://faun.pub/compliance-and-delegation-of-azure-locks-through-azure-policy-9f464d40faee).
- Before implementing Azure Locks make sure you have read the following documentation [Considerations before applying your locks](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/lock-resources?tabs=json&WT.mc_id=AZ-MVP-5003548#considerations-before-applying-your-locks).

Compliance and delegation of Azure Locks through Azure Policy

---

Policies/Compute/Deploy Microsoft IaaSAntimalware extension for Custom Windows Images/Deploy Microsoft IaaSAntimalware extension for Custom Windows Images.json
Policies/Compute/Deploy Microsoft IaaSAntimalware extension for Custom Windows Images/Deploy Microsoft IaaSAntimalware extension for Custom Windows Images.parameters.json
Policies/Compute/Deploy Microsoft IaaSAntimalware extension for Custom Windows Images/Deploy Microsoft IaaSAntimalware extension for Custom Windows Images.rules.json

This new policy allow custom Windows images.
An addition to the builtin policy that only allows a select list of marketplace images: https://www.azadvertizer.net/azpolicyadvertizer/2835b622-407b-4114-9198-6f7064cbe0dc.html

IaaSAntimalware ext for Custom Windows Servers

---

Policies/Network/prevent-delete-private-dns-zone/azurepolicy.json
Policies/Network/prevent-delete-private-dns-zone/azurepolicy.rules.json

fixing a defect where the policy definition only protected against explicit delete action of the Private DNS Zone resource... this update will also protect against cascade deletes from the resource group level.

fixed cascadeBehavior

---

Policies/Monitoring/Diag2LAW/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace.json
Policies/Monitoring/Diag2LAW/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace.parameters.json
Policies/Monitoring/Diag2LAW/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace/Deploy Diagnostic Settings for Managed HSM Key Vault to Log Analytics workspace.rules.json

Updated deployment type to be correct as well as added support for audit and allLogs logs categoryGroups, plus other tweaks.

Fixed MHSM policy errors

---

Policies/Authorization/Configure ReadOnly lock for API Management's subnet/Configure ReadOnly lock for API Management's subnet.json
Policies/Authorization/Configure ReadOnly lock for API Management's subnet/Configure ReadOnly lock for API Management's subnet.parameters.json
Policies/Authorization/Configure ReadOnly lock for API Management's subnet/Configure ReadOnly lock for API Management's subnet.rules.json
Policies/Authorization/Create Delete Lock on specified Azure VMs/Create Delete Lock on specified Azure VMs.json
Policies/Authorization/Create Delete Lock on specified Azure VMs/Create Delete Lock on specified Azure VMs.parameters.json
Policies/Authorization/Create Delete Lock on specified Azure VMs/Create Delete Lock on specified Azure VMs.rules.json
Policies/Authorization/Deploy CanNotDelete Resource Lock on Resource Groups/Deploy CanNotDelete Resource Lock on Resource Groups.json
Policies/Authorization/Deploy CanNotDelete Resource Lock on Resource Groups/Deploy CanNotDelete Resource Lock on Resource Groups.parameters.json
Policies/Authorization/Deploy CanNotDelete Resource Lock on Resource Groups/Deploy CanNotDelete Resource Lock on Resource Groups.rules.json
Policies/Authorization/Deploy Purview account CanNotDelete lock/Deploy Purview account CanNotDelete lock.json
Policies/Authorization/Deploy Purview account CanNotDelete lock/Deploy Purview account CanNotDelete lock.parameters.json
Policies/Authorization/Deploy Purview account CanNotDelete lock/Deploy Purview account CanNotDelete lock.rules.json

Added 4 policies to deploy resource locks on different resource types for different scenarios.
Read policy descriptions for further info.

Added resource lock policies

---

Policies/Storage/Audit-Storage-EncryptionWithoutHSM/azurepolicy.json
Policies/Storage/Audit-Storage-EncryptionWithoutHSM/azurepolicy.parameters.json
Policies/Storage/Audit-Storage-EncryptionWithoutHSM/azurepolicy.rules.json
Policies/Storage/Configure Blob Soft Delete/azurepolicy.json
Policies/Storage/Configure Blob Soft Delete/azurepolicy.parameters.json
Policies/Storage/Configure Blob Soft Delete/azurepolicy.rules.json
Policies/Storage/Configure Container Soft Delete/azurepolicy.json
Policies/Storage/Configure Container Soft Delete/azurepolicy.parameters.json
Policies/Storage/Configure Container Soft Delete/azurepolicy.rules.json
Policies/Storage/Deny permanent delete for soft deleted items/azurepolicy.json
Policies/Storage/Deny permanent delete for soft deleted items/azurepolicy.parameters.json
Policies/Storage/Deny permanent delete for soft deleted items/azurepolicy.rules.json
Policies/Storage/Deploy SAS expiration policy on storage account/azurepolicy.json
Policies/Storage/Deploy SAS expiration policy on storage account/azurepolicy.parameters.json
Policies/Storage/Deploy SAS expiration policy on storage account/azurepolicy.rules.json
Policies/Storage/Enforce storage account naming convention/azurepolicy.json
Policies/Storage/Enforce storage account naming convention/azurepolicy.parameters.json
Policies/Storage/Enforce storage account naming convention/azurepolicy.rules.json
Policies/Storage/Storage accounts should enable AAD authorization in the Azure portal/azurepolicy.json
Policies/Storage/Storage accounts should enable AAD authorization in the Azure portal/azurepolicy.parameters.json
Policies/Storage/Storage accounts should enable AAD authorization in the Azure portal/azurepolicy.rules.json
Policies/Storage/Storage accounts should prevent allowed copy scope outside AAD tenant/azurepolicy.json
Policies/Storage/Storage accounts should prevent allowed copy scope outside AAD tenant/azurepolicy.parameters.json
Policies/Storage/Storage accounts should prevent allowed copy scope outside AAD tenant/azurepolicy.rules.json

Added 8 policies for storage accounts.
See policy descriptions for further info.

Storage account policies for various purposes

---

Policies/Databricks/Audit - Databricks should use customer-managed key for encrypting DBFS/azurepolicy.json
Policies/Databricks/Audit - Databricks should use customer-managed key for encrypting DBFS/azurepolicy.parameters.json
Policies/Databricks/Audit - Databricks should use customer-managed key for encrypting DBFS/azurepolicy.rules.json
Policies/Databricks/Audit - Databricks should use customer-managed key for encrypting managed services/azurepolicy.json
Policies/Databricks/Audit - Databricks should use customer-managed key for encrypting managed services/azurepolicy.parameters.json
Policies/Databricks/Audit - Databricks should use customer-managed key for encrypting managed services/azurepolicy.rules.json

Databricks should use customer-managed key for encrypting DBFS and managed services

Databricks policies for auditing CMK encryption

---

Policies/Network/deploy-private-dnszone-private-endpoints-generic/azurepolicy.json
Policies/Network/deploy-private-dnszone-private-endpoints-generic/azurepolicy.parameters
Policies/Network/deploy-private-dnszone-private-endpoints-generic/azurepolicy.rules.json

Adding new Azure Policy to manage DNS integration for any kind of Pri…vate Endpoint.

New Azure Policy to manage DNS integration for any kind of PE

---

policyDefinitions/Network/deploy-a-traffic-analytics-enabled-flow-log-resource-with-target-tagged-network-security-group/azurepolicy.json
policyDefinitions/Network/deploy-a-traffic-analytics-enabled-flow-log-resource-with-target-tagged-network-security-group/azurepolicy.parameters.json
policyDefinitions/Network/deploy-a-traffic-analytics-enabled-flow-log-resource-with-target-tagged-network-security-group/azurepolicy.rules.json

This policy allows gradual rollout of Flow logging with Traffic Analytics enabled based on tag presence requirement on NSGs within a policy scope.

Add policy to deploy Traffic Analytics enabled Flow Logs on tagged NSGs.

---

policyDefinitions/Authorization/allowed-role-definitions-for-specific-principal-ids/azurepolicy.json
policyDefinitions/Authorization/allowed-role-definitions-for-specific-principal-ids/azurepolicy.parameters.json
policyDefinitions/Authorization/allowed-role-definitions/azurepolicy.json
policyDefinitions/Authorization/allowed-role-definitions/azurepolicy.parameters.json
policyDefinitions/Authorization/disallowed-role-definitions/azurepolicy.json
policyDefinitions/Authorization/disallowed-role-definitions/azurepolicy.parameters.json

Check Policies in Authorization folder for duplicates, superseded, logic.
- Made some textual changes

Validate Authorization policies

---

policyDefinitions/Container Registry/container-registries-enable-zone-redundancy/azurepolicy.json
policyDefinitions/Container Registry/container-registries-enable-zone-redundancy/azurepolicy.parameters.json
policyDefinitions/Container Registry/container-registries-enable-zone-redundancy/azurepolicy.rules.json

[New] Container Registries enable zone redundancy

---

policyDefinitions/Container Registry/container-registries-enable-retention-policy/azurepolicy.json
policyDefinitions/Container Registry/container-registries-enable-retention-policy/azurepolicy.parameters.json
policyDefinitions/Container Registry/container-registries-enable-retention-policy/azurepolicy.rules.json

[New] Container Registries enable retention policy

---

Scripts/Confirm-PolicyDefinitionIsValid.ps1

**Changes Made:**
Modified the Confirm-PolicyDefinitionIsValid function to incorporate distinct ErrorCodes for detecting warnings and errors during policy validation.
**Reason for the Change:**
In the existing version, the Confirm-PolicyDefinitionIsValid function consistently returns a success status regardless of whether warnings or errors are detected during policy validation. This behavior can lead to scenarios where issues are only identifiable by examining log files, which is not an ideal situation for maintaining code quality.

feat: Update Confirm-PolicyDefinitionIsValid for Enhanced Error Handling

---

policyDefinitions/Container Registry/container-registries-enable-trust-policy/azurepolicy.json
policyDefinitions/Container Registry/container-registries-enable-trust-policy/azurepolicy.parameters.json
policyDefinitions/Container Registry/container-registries-enable-trust-policy/azurepolicy.rules.json

[New] Container Registries enable trust policy

---

policyDefinitions/Container Registry/container-registries-enable-soft-delete-policy/azurepolicy.json
policyDefinitions/Container Registry/container-registries-enable-soft-delete-policy/azurepolicy.parameters.json
policyDefinitions/Container Registry/container-registries-enable-soft-delete-policy/azurepolicy.rules.json

[New] Container Registries enable soft delete policy

---

policyDefinitions/Monitoring/log-analytics-workspace-require-retention-in-days/azurepolicy.json
policyDefinitions/Monitoring/log-analytics-workspace-require-retention-in-days/azurepolicy.parameters.json
policyDefinitions/Monitoring/log-analytics-workspace-require-retention-in-days/azurepolicy.rules.json

[New] Log Analytics Workspace require retention in days

---

policyDefinitions/SQL/deny-changes-to-sqlmi-long-term-backup-retention/azurepolicy.json
policyDefinitions/SQL/deny-changes-to-sqlmi-long-term-backup-retention/azurepolicy.parameters.json
policyDefinitions/SQL/deny-changes-to-sqlmi-long-term-backup-retention/azurepolicy.rules.json

Adding a new policy to deny changes to long term backup retention policies on SQL Managed Instance

[NEW] SQLMI Long Term Backup Retention

---

policyDefinitions/Monitoring/deny-change-of-retention-days-in-log-analytics-workspace/azurepolicy.json

- Refactor policy description to avoid the use of "deny".
- Update allowedValues and set default to "Audit" as per contribution guidelines.

Update policy desc & align values with contrib guide.

---

policyDefinitions/Authorization/allowed-role-definitions-for-specific-principal-ids/azurepolicy.json
policyDefinitions/Authorization/allowed-role-definitions-for-specific-principal-ids/azurepolicy.parameters.json
policyDefinitions/Authorization/allowed-role-definitions/azurepolicy.json
policyDefinitions/Authorization/allowed-role-definitions/azurepolicy.parameters.json
policyDefinitions/Authorization/disallowed-role-definitions/azurepolicy.json
policyDefinitions/Authorization/disallowed-role-definitions/azurepolicy.parameters.json

Minor updates to authorization policies as part of review:
- Add quotes
- Fix typo

Minor updates to authorization policies

---

README.md

First commit and PR and I'm delighted to be able to give back to this project that has helped me so much.

Changed wording to improve clarity

---

policySetDefinitions/regulatorycompliance-nzism/README.md
policySetDefinitions/regulatorycompliance-nzism/deploy-initiative.ps1
policySetDefinitions/regulatorycompliance-nzism/nzism3.6.definitions.json
policySetDefinitions/regulatorycompliance-nzism/nzism3.6.groups.json
policySetDefinitions/regulatorycompliance-nzism/nzism3.6.parameters.json

New Zealand Information Security Manual (NZISM) v3.6 Regulatory Compliance Initiative designed for NZ public sector agencies to measure their Azure environments against the NZISM.
This policy and repo will be used in future as the publication point for new versions going forward, and the builtin policies will be deprecated.  Documentation on MS Learn will be updated to point to this repo and the GCSB website as the places to download the latest versions of this compliance policy initaitive.
Only builtin policies are used for this initiative - no custom policies defined as yet.

1st edition of nzism v3.6 regulatoryCompliance

---

.github/workflows/confirm-policy-definition-validity.yaml

Updated the version to the latest available.
Improved our yml logic to be capable of handling the escape characters added to the file names.

Fix tj-actions changed files

---

policyDefinitions/Storage/deploy-sas-expiration-policy-on-storage-account/azurepolicy.json
policyDefinitions/Storage/deploy-sas-expiration-policy-on-storage-account/azurepolicy.rules.json

The DINE property uses the same type under the IF and then condition, which makes the name property required

adding the name property under the then section

---

policySetDefinitions/regulatorycompliance-nzism/README.md

this fixes the linting issues in the NZISM readme.

fix: markdown lint rules for NZISM readme

---

policyDefinitions/Compute/deploy-windows-vm-app/azurepolicy.json
policyDefinitions/Compute/deploy-windows-vm-app/azurepolicy.rules.json

Added role definition:
b9331d33-8a36-4f8c-b097-4f54124fdb44 (Managed Applications Reader)

Fix issue 451

---

policyDefinitions/Network/deny-creation-of-vnets-that-don't-follow-a-pre-defined-naming-convention/azurepolicy.json
policyDefinitions/Network/deny-creation-of-vnets-that-don't-follow-a-pre-defined-naming-convention/azurepolicy.parameters.json

typ0 metadata

---

policyDefinitions/SQL/deny-sql-database-transparent-data-encryption-disablement/azurepolicy.json
policyDefinitions/SQL/deny-sql-database-transparent-data-encryption-disablement/azurepolicy.rules.json

adding condition to evaluate only non-master databases

adding condition to evaluateonly non-master databases

---

policyDefinitions/App Configuration/app-configuration-stores-should-should-have-soft-delete-enabled-of-7-days/azurepolicy.json
policyDefinitions/App Configuration/app-configuration-stores-should-should-have-soft-delete-enabled-of-7-days/azurepolicy.parameters.json
policyDefinitions/App Configuration/app-configuration-stores-should-should-have-soft-delete-enabled-of-7-days/azurepolicy.rules.json

Adding pending modification to parametrize the retention days value

creation of parameter for the retention days value

---

policyDefinitions/Key Vault/deny-kv-resourceaccess-arm-template-deployment/azurepolicy.json
policyDefinitions/Key Vault/deny-kv-resourceaccess-arm-template-deployment/azurepolicy.parameters.json
policyDefinitions/Key Vault/deny-kv-resourceaccess-arm-template-deployment/azurepolicy.rules.json
policyDefinitions/Key Vault/deny-kv-resourceaccess-disk-encryption/azurepolicy.json
policyDefinitions/Key Vault/deny-kv-resourceaccess-disk-encryption/azurepolicy.parameters.json
policyDefinitions/Key Vault/deny-kv-resourceaccess-disk-encryption/azurepolicy.rules.json
policyDefinitions/Key Vault/deny-kv-resourceaccess-virtual-machine-deployment/azurepolicy.json
policyDefinitions/Key Vault/deny-kv-resourceaccess-virtual-machine-deployment/azurepolicy.parameters.json
policyDefinitions/Key Vault/deny-kv-resourceaccess-virtual-machine-deployment/azurepolicy.rules.json

Created custom policy definitions to enforce disabling Resource Access to Key Vault.

Policy Definitions to disable Key Vault resource access

---

policyDefinitions/SQL/enforce-postgresql-administrator-group-principal-name-prefix/azurepolicy.json
policyDefinitions/SQL/enforce-postgresql-administrator-principal-types/azurepolicy.json

unique guids d78f353a-a5e7-4747-8d31-62f361bafac5,6,7
